=== jhonatanrestrepo/momento_valorativo/biblioteca.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="bib">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string" maxOccurs="unbounded" minOccurs="1"/>
                            <xs:element name="autor" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="apellido" minOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="([a-z])*"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="nombre" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                    <xs:attribute name="cedula" type="xs:ID" use="required"/>
                                    <xs:attribute name="foto" type="xs:string" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="editorial" maxOccurs="unbounded" minOccurs="1"/>
                            <xs:element name="precio" maxOccurs="unbounded" minOccurs="1"/>


                        </xs:sequence>
                        <xs:attribute name="cod_pais">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="ESP"/>
                                    <xs:enumeration value="FRA"/>
                                    <xs:enumeration value="ITA"/>
                                    <xs:enumeration value="ALE"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="anyo" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="nombre" type="xs:string" use="required"/>
            <xs:attribute name="centro" type="xs:string" use="required"/>
            <xs:attribute name="portada" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== jhonatanrestrepo/momento_valorativo/biblioteca.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--<!DOCTYPE bib SYSTEM "reglas_biblioteca.dtd">-->
<?xml-stylesheet type="text/xsl" href="biblioteca.xsl" ?>
<bib xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="biblioteca.xsd" nombre="Tomás Carrasquilla" centro="poblado" portada="https://scontent.feoh3-1.fna.fbcdn.net/v/t39.30808-6/301153716_452836323563323_5646586074448291472_n.jpg?_nc_cat=109&amp;ccb=1-7&amp;_nc_sid=e3f864&amp;_nc_ohc=NJclP7e_OQQAX_2m_XS&amp;_nc_ht=scontent.feoh3-1.fna&amp;oh=00_AfDDK2o_SMQOTDtW7eyKc9Q37ymhK47EY01IVu272zTZcg&amp;oe=63697818">
    <libro anyo="1990" cod_pais="ALE">
        <titulo>TCP/IP Illustrated</titulo>
        <autor cedula="NUIP10" foto="https://crearmiempresa.es/wp-content/uploads/2015/07/frases-de-steve-jobs.jpg">
            <apellido>stevens</apellido>
            <nombre>W.</nombre>
        </autor>
        <editorial>Addison-Wesley</editorial>
        <precio>65.95</precio>
    </libro >
    <libro anyo="1992" cod_pais="ESP">
        <titulo>Advanced Programming for Unix environment</titulo>
        <autor cedula="NUIP11">
            <apellido>stevens</apellido>
            <nombre>W.</nombre>
        </autor>
        <editorial>Addison-Wesley</editorial>
        <precio>65.95</precio>
    </libro>
    <libro anyo="2000" cod_pais="ALE">
        <titulo>Data on the Web</titulo>
        <autor cedula="NUIP12">
            <apellido>abiteboul</apellido>
            <nombre>Serge</nombre>
        </autor>
        <autor cedula="NUIP13">
            <apellido>buneman</apellido>
            <nombre>Peter</nombre>
        </autor>
        <autor cedula="NUIP14">
            <apellido>suciu</apellido>
            <nombre>Dan</nombre>
        </autor>
        <editorial>Morgan Kaufmann editorials</editorial>
        <precio>39.95</precio>
    </libro>
    <libro anyo="1999" cod_pais="FRA">
        <titulo> Economics of Technology for Digital TV</titulo>
        <autor cedula="NUIP15">
            <apellido>gerbarg</apellido>
            <nombre>Darcy</nombre>
        </autor>
        <editorial>Kluwer Academic editorials</editorial>
        <precio>129.95</precio>
    </libro>
</bib>
